platform :ios, '15.0'

inhibit_all_warnings!
use_frameworks!

target 'JPMovieWriter_Example' do
  pod 'JPBasic/JPProgressHUD'
  pod 'JPImageresizerView'
  pod 'JPCrop'
#  pod 'GPUImage', '~> 0.1.7'
  pod 'GPUImage_Local', :path => './GPUImage_Local'
  pod 'pop'
  pod 'WCDB.swift', '~> 1.0.8.2'
  pod 'Kingfisher', '~> 7.4.1'
  pod 'YYText'
  
#  https://blog.csdn.net/crasowas/article/details/129901398
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
  
end
